{
  "openapi": "3.0.1",
  "info": {
    "title": "Network API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local"
    },
    {
      "url": "https://developmentapi.ienterprise.info/newblack",
      "description": "Dev"
    },
    {
      "url": "https://stagingapi.ienterprise.com/newblack",
      "description": "Staging"
    }
  ],
  "paths": {
    "/device/{storeNumber}": {
      "get": {
        "tags": [
          "new-black-device-api"
        ],
        "operationId": "findWatchTowerDevicesByStoreNumber",
        "parameters": [
          {
            "name": "storeNumber",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseListNewBlackDevice"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseListNewBlackDevice": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/NewBlackDevice"
            }
          }
        }
      },
      "NewBlackDevice": {
        "type": "object",
        "properties": {
          "ID": {
            "type": "integer",
            "format": "int64"
          },
          "Name": {
            "type": "string"
          },
          "HardwareID": {
            "type": "string"
          },
          "OrganizationUnitID": {
            "type": "string"
          },
          "OrganizationUnitName": {
            "type": "string"
          },
          "WatchtowerIOConnected": {
            "type": "string"
          },
          "WatchtowerIOLastSeen": {
            "type": "string"
          },
          "WatchtowerConnected": {
            "type": "string"
          },
          "WatchtowerLastSeen": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "basicAuth": {
        "type": "http",
        "scheme": "basic"
      }
    }
  }
}
